name: Build and Deploy to Server

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Clean up node_modules for production
        run: npm prune --production

      - name: Deploy to Server via rsync
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: '/.git/, /.github/, .env'

      - name: Restart Application on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Nếu Node cài bằng nvm, load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Thêm path cho npm & pm2 nếu cần
            export PATH=$PATH:/usr/local/bin

            cd ${{ secrets.TARGET_DIR }}
            echo "Restarting the application with PM2..."

            # Xóa các process errored cũ (nếu có)
            pm2 delete mktproxy || true

            # Cài pm2 nếu chưa có
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2

            # Restart hoặc start ứng dụng
            pm2 start npm --name "mktproxy" -- run start
